spring.application.name=makemytrip
server.port=8080

spring.mongodb.uri=mongodb+srv://admin:admin@main.jonrc2o.mongodb.net/makemytrip?appName=main
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration